# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_desc', models.TextField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('data_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='Images/None/No-img.gif', upload_to='Images/')),
            ],
        ),
    ]
